### ISSUE TITLE
Add support for portal specific manifests

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#104]
1. By default, use the `manifest.yml` in the root of the app for viewing and editing
2. If a `manifest.yml.$OOD_PORTAL` exists, that is used for both viewing and editing by the dashboard

So for example, for OnDemand and AweSim, an app could have three different manifests:

1. `manifest.yml` a default manifest
2. `manifest.yml.awesim` an AweSim specific manifest (`OOD_PORTAL=ondemand`)
3. `manifest.yml.ondemand` an OnDemand specific manifest (`OOD_PORTAL=ondemand`)

This could obviate the need for special deployment directions for apps that need different manifests based on the portal they are deployed to.

Short sighted though, as we still have custom initializers and custom .env files for configuration, and some that are OSC specific, and OOD_PORTAL mentions nothing of OSC.

**Comment by ericfranz** [comment]
Another option is portal specific overrides in manifest.yml

```yaml
---
name: System Status
description: |-
  System Status of OSC Clusters
category: Clusters
icon: fa://tachometer

overrides:
  awesim:
    category: Ohio Supercomputer Center
```
